### ISSUE TITLE
[Proxy] Basic authentication for nodes is not supported

### ISSUE THREAD

**Issue by 6l20** [ConsenSys/quorum-key-manager#471]
### Describe the bug

A node url with correct basic auth may not be accessed and returns the following :

```
{
    "jsonrpc": "2.0",
    "result": null,
    "error": {
        "code": -32001,
        "message": "Invalid downstream HTTP status",
        "data": {
            "message": "Unauthorized",
            "status": 401
        }
    },
    "id": "1"
}
```

### Configuration

Using the following manifest :

```
- kind: Vault
  type: hashicorp
  name: hashicorp-quorum
  #allowed_tenants: [tenant1, tenant2]
  specs:
    mount_point: orchestrate
    address: http://vault.orchestrate.svc.cluster.local:8200
    token_path: /vault/token/.agent-orchestrate-vault-token
    namespace: "orchestrate"
- kind: Vault
  type: hashicorp
  name: hashicorp-kv-v2
  # allowed_tenants: [tenant1, tenant2]
  specs:
    mount_point: secret
    address: http://vault.orchestrate.svc.cluster.local:8200
    token_path: /vault/token/.agent-orchestrate-vault-token
    namespace: "orchestrate"
- kind: Store
  type: key
  name: hashicorp-keys
  #allowed_tenants: [tenant1, tenant2]
  specs:
    vault: hashicorp-quorum
- kind: Store
  type: key
  name: local-keys
  #allowed_tenants: [tenant1, tenant2]
  specs:
    vault: hashicorp-quorum
- kind: Store
  type: secret
  name: hashicorp-secrets
  # allowed_tenants: []
  specs:
    vault: hashicorp-kv-v2
- kind: Store
  type: ethereum
  name: eth-accounts
  #allowed_tenants: [tenant1, tenant2]
  specs:
    key_store: hashicorp-keys
- kind: Node
  name: quorum-node
  specs:
    rpc:
      addr: https://user1:$apr1$Q8OrooKZ$apGn.ZWMHixZwq4UWfZck1@quorum1.ops.consensys.net/
    tessera:
      addr: http://user1:secret@quorum2-tessera.ops.consensys.net/
- kind: Node
  name: quorum1-node
  specs:
    rpc:
      addr: https://user1:$apr1$Q8OrooKZ$apGn.ZWMHixZwq4UWfZck1@quorum1.ops.consensys.net/
    tessera:
      addr: http://user1:secret@quorum2-tessera.ops.consensys.net/
- kind: Node
  name: quorum2-node
  specs:
    rpc:
      addr: http://user1:$apr1$Q8OrooKZ$apGn.ZWMHixZwq4UWfZck1@quorum2.ops.consensys.net/
    tessera:
      addr: http://user1:secret@quorum2-tessera.ops.consensys.net/
- kind: Node
  name: quorum11-node
  specs:
    rpc:
      addr: https://user1:secret@quorum1.ops.consensys.net/
    tessera:
      addr: http://user1:secret@quorum2-tessera.ops.consensys.net/
- kind: Node
  name: quorum21-node
  specs:
    rpc:
      addr: http://user1:secret@quorum2.ops.consensys.net/
    tessera:
      addr: http://user1:secret@quorum2-tessera.ops.consensys.net/
- kind: Node
  name: quorum3-node
  specs:
    rpc:
      addr: http://quorum3.ops.consensys.net/
    tessera:
      addr: http://user1:secret@quorum2-tessera.ops.consensys.net/

- kind: Node
  name: besu-node
  specs:
    rpc:
      addr: http://user1:secret@besu1.ops.consensys.net/

- kind: Node
  name: geth-node
  specs:
    rpc:
      addr: http://user1:secret@geth.ops.consensys.net/
- kind: Role
  name: anonymous
  specs:
    permissions:
      - "proxy:nodes"

- kind: Role
  name: guest
  specs:
    permissions:
      - "read:*"

- kind: Role
  name: signer
  specs:
    permissions:
      - "read:*"
      - "sign:keys"
      - "sign:ethereum"

- kind: Role
  name: admin
  specs:
    permissions:
      - "*:*"
```

Description of what actually happens 

When sending that command to a port-forwarded QKM `
docker.io/consensys/quorum-key-manager:v21.12.1`

```
curl --location --request POST 'http://localhost:8080/nodes/quorum21-node' \
--header 'Authorization: Basic YWRtaW4tdXNlcg==' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_chainId",
    "params": [],
    "id": "1"
}'
```

**Expected result**

```
{
    "jsonrpc": "2.0",
    "result": "0xa",
    "error": null,
    "id": "1"
}
```

**Actual result**

```
{
    "jsonrpc": "2.0",
    "result": null,
    "error": {
        "code": -32001,
        "message": "Invalid downstream HTTP status",
        "data": {
            "message": "Unauthorized",
            "status": 401
        }
    },
    "id": "1"
}
```
