### ISSUE TITLE
Error ST100: failed to create Hashicorp key

### ISSUE THREAD

**Issue by capri-san** [ConsenSys/quorum-key-manager#571]
I am testing Quorum Key Manager with Hashicorp Vault. I am using Quorum Hashicorp Plugin to be able to manage ethereum keys, sign transactions, etc., using the following vault image "consensys/quorum-hashicorp-vault-plugin:latest" taken from https://github.com/ConsenSys/quorum-hashicorp-vault-plugin/blob/main/docker-compose.yml. I've been able to have both services connected running, and i'm able to get, create, delete secrets from QKM, but when I try to create a key, or an ethereum account issuing an API call like this:

```
curl -X POST --data '{"keyId":"my-key-account"}' -H "Content-Type:application/json" 'http://localhost:8080/stores/my-ethereum-store/ethereum'
```
I get the following error:
```
{"message":"ST100: failed to create Hashicorp key","code":"ST100"}
```
Looking into QKM log, the following error ir shown:
```
key-manager_1  | 2022-08-04T12:42:38.593Z   ERROR   stores  failed to create Hashicorp key  {"name": "hashicorp-keys", "vault": "hashicorp-vault", "secret_store": "", "id": "my-key-account", "error": "ST100: Error making API request.\n\nURL: PUT http://vault:8200/v1/secret/keys\nCode: 404. Errors:\n\n"}
key-manager_1  | 2022-08-04T12:42:38.593Z   INFO    auth.accesslog  172.20.0.1 - - [04/Aug/2022:12:42:38 +0000] "POST /stores/my-ethereum-store/ethereum HTTP/1.1" 404 66
```
My QKM manifest file is this:
```
- kind: Vault
  type: hashicorp
  name: hashicorp-vault
  specs:
    mount_point: secret
    address: http://vault:8200
    token: xxxxxxxxxxxxxxxxxxx

- kind: Store
  type: secret
  name: hashicorp-secrets
  specs:
    vault: hashicorp-vault

- kind: Store
  type: key
  name: hashicorp-keys
  specs:
    vault: hashicorp-vault

- kind: Store
  type: ethereum
  name: my-ethereum-store
  specs:
    key_store: hashicorp-keys

- kind: Node
  name: besu-node
  specs:
    rpc:
      addr: http://localhost:8545
    tessera:
      addr: http://localhost:9080
```
Of course the token is correctly set, and when my vault is started, looks like the plugin is correctly started and binded to the vault:
```
vault_1           | 2022-08-04T10:37:04.725Z [DEBUG] secrets.quorum-hashicorp-vault-plugin.quorum-hashicorp-vault-plugin_9da34603.quorum-hashicorp-vault-plugin: starting plugin: path=/vault/plugins/quorum-hashicorp-vault-plugin args=["/vault/plugins/quorum-hashicorp-vault-plugin"]
vault_1           | 2022-08-04T10:37:04.725Z [DEBUG] secrets.quorum-hashicorp-vault-plugin.quorum-hashicorp-vault-plugin_9da34603.quorum-hashicorp-vault-plugin: plugin started: path=/vault/plugins/quorum-hashicorp-vault-plugin pid=103
vault_1           | 2022-08-04T10:37:04.725Z [DEBUG] secrets.quorum-hashicorp-vault-plugin.quorum-hashicorp-vault-plugin_9da34603.quorum-hashicorp-vault-plugin: waiting for RPC address: path=/vault/plugins/quorum-hashicorp-vault-plugin
vault_1           | 2022-08-04T10:37:04.854Z [INFO]  expiration: revoked lease: lease_id=sys/wrapping/wrap/hf12037a61bf51568f888f165bd13fdd59d6aacdd6d418421718bd22e87e2365b
vault_1           | 2022-08-04T10:37:04.858Z [DEBUG] secrets.quorum-hashicorp-vault-plugin.quorum-hashicorp-vault-plugin_9da34603.quorum-hashicorp-vault-plugin.quorum-hashicorp-vault-plugin: 2022-08-04T10:37:04.858Z [DEBUG] plugin address: network=unix address=/tmp/plugin644251873
vault_1           | 2022-08-04T10:37:04.858Z [DEBUG] secrets.quorum-hashicorp-vault-plugin.quorum-hashicorp-vault-plugin_9da34603.quorum-hashicorp-vault-plugin: using plugin: version=4
```
Any ideas on what can be the problem?

### Configuration
Docker images used:
* consensys/quorum-hashicorp-vault-plugin:latest
* consensys/quorum-key-manager:latest
* postgres:13.4-alpine

Docker-compose files to run the services directly taken from consensys repos, with minimum modifications to target the same network:
* https://github.com/ConsenSys/quorum-hashicorp-vault-plugin/blob/main/docker-compose.yml
* https://github.com/ConsenSys/quorum-key-manager/blob/main/docker-compose.yml

### Steps to reproduce

1. Run Hashicorp Vault
2. Get the token from the vault and add it to manifest.yaml file
3. Run QKM
4. Issue an ethereum account create command: `curl -X POST --data '{"keyId":"my-key-account"}' -H "Content-Type:application/json" 'http://localhost:8080/stores/my-ethereum-store/ethereum'`

**Actual result**

{"message":"ST100: failed to create Hashicorp key","code":"ST100"}

**Expected result**

A JSON object representing a new ethereum account

**Comment by ggarri** [comment]
Hi @capri-san 

At first sight I see you are using `secret/` as `mount_point` for your hashicorp vault plugin. I believe that cannot be possible because `/secret` it is the default mounting point for kv-v2 storage. In case you are using our hashicorp plugin I would expect it to be `quorum` instead, as you could see in the [quorum-hashicorp-vault-plugin docker-compose](https://github.com/ConsenSys/quorum-hashicorp-vault-plugin/blob/main/docker-compose.yml#L74) . 

Could you try again by modifying your manifest and write the follow Vault settings:
```
- kind: Vault
  type: hashicorp
  name: hashicorp-vault
  specs:
    mount_point: quorum
    address: http://vault:8200
    token: xxxxxxxxxxxxxxxxxxx
```

**Comment by jorgesjv** [comment]
Hi @ggarri 

Thanks for the answer, i've fixed the manifest file like you said, now I can create keys and eth accounts correctly, but now the problem is that can't operate with secrets. It seems like the secret store was created but can't create any secrets.

When i execute the GET.
```
curl -X GET 'http://localhost:8080/stores/hashicorp-secrets/secrets'
``` 

I get this, so i think that is well created the store.

```
{"data":[],"paging":{}}
```

But when i try to create a secret using POST.
```
curl -X POST --data '{"tags":{"property1":"string","property2":"string"},"value":"my-super-password"}' -H "Content-Type:application/json" 'http://localhost:8080/stores/hashicorp-secrets/secrets/my-super-secret'
```

I get this error.

```
{"message":"ST100: failed to create Hashicorp secret","code":"ST100"}
```

And the QKM log shows this.

```
2022-08-09T09:21:03.631Z        ERROR   stores  failed to create Hashicorp secret       {"name": "hashicorp-secrets", "vault": "hashicorp-vault", "id": "my-super-secret", "error": "ST100: Error making API request.\n\nURL: PUT http://vault:8200/v1/quorum/data/my-super-secret\nCode: 404. Errors:\n\n* 1 error occurred:\n\t* unsupported path\n\n"}
2022-08-09T09:21:03.631Z        INFO    auth.accesslog  172.18.0.1 - - [09/Aug/2022:09:21:03 +0000] "POST /stores/hashicorp-secrets/secrets/my-super-secret HTTP/1.1" 404 69
```

Any idea? Thanks in advance

**Comment by ggarri** [comment]
Hi @jorgesjv 

Can you share your latest manifest? In order to handle secrets, it is required to have two defined Vaults, one for keys and another for secrets. So you  need something like the following:

```
- kind: Vault
  type: hashicorp
  name: hashicorp-vault
  specs:
    mount_point: secret
    address: http://vault:8200
    token: xxxxxxxxxxxxxxxxxxx

- kind: Store
  type: secret
  name: hashicorp-secrets
  specs:
    vault: hashicorp-vault
```
